<?php
/**
 * PHP Magazin: Artikel über Plates
 *
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       https://www.travello.de/
 * @copyright  Travello GmbH, 2017
 */
?>
<html>
<head>
    <title><?= $this->e($title) ?></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
<div class="container">
    <h1><?= $this->e($title) ?></h1>
    <ul class="nav nav-tabs">
        <?php foreach ($pages as $pageUrl => $pageName): ?>
            <li>
                <a href="<?= $this->e($pageUrl) ?>.php">
                    <?= $this->e($pageName) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <p>
        Eine wunderbare Heiterkeit hat meine ganze Seele eingenommen, gleich den
        süßen Frühlingsmorgen, die ich mit ganzem Herzen genieße.
    </p>
    <p>
        Ich bin allein und freue mich meines Lebens in dieser Gegend, die für
        solche Seelen geschaffen ist wie die meine. Ich bin so glücklich, mein
        Bester, so ganz in dem Gefühle von ruhigem Dasein versunken, daß meine
        Kunst darunter leidet. Ich könnte jetzt nicht zeichnen, nicht einen
        Strich, und bin nie ein größerer Maler gewesen als in diesen
        Augenblicken.
    </p>
    <p>
        Wenn das liebe Tal um mich dampft, und die hohe Sonne an der Oberfläche
        der undurchdringlichen Finsternis meines Waldes ruht, und nur einzelne
        Strahlen sich in das innere Heiligtum stehlen, ich dann im hohen Grase
        am fallenden Bache liege, und näher an der Erde tausend mannigfaltige
        Gräschen mir merkwürdig werden; wenn ich das Wimmeln der kleinen Welt
        zwischen Halmen, die unzähligen, unergründlichen Gestalten der Würmchen,
        der Mückchen näher an meinem Herzen fühle, und fühle die Gegenwart des
        Allmächtigen, der uns nach seinem Bilde schuf, das Wehen des
        Alliebenden, der uns in ewiger Wonne schwebend trägt und erhält; mein
        Freund!
    </p>
</div>
</body>
</html>
