<?php

/**
 * PHP Magazin: Artikel über Plates
 *
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       https://www.travello.de/
 * @copyright  Travello GmbH, 2017
 */
?>
<html>
<head>
    <title><?= $this->e($title) ?></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
<div class="container">
<?= $this->fetch('layouts::header', ['pages' => $pages]) ?>
<div class="row">
    <div class="col-sm-9">
        <?= $this->section('content') ?>
    </div>
    <div class="col-sm-3">
        <?= $this->fetch('layouts::sidebar') ?>
    </div>
</div>
</div>
<?= $this->fetch('layouts::footer') ?>
</body>
</html>
