<?php

/**
 * PHP Magazin: Artikel über Plates
 *
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       https://www.travello.de/
 * @copyright  Travello GmbH, 2017
 */
?>
<div class="well well-sm">
    <h3>Erstens</h3>
    <p>
        Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen
        ihnen Profi was sie sind. Ich lese nicht sehr viele Zeitungen, aber ich
        habe gehört viele Situationen. Erstens: wir haben nicht offensiv
        gespielt.
    </p>
</div>

<div class="well well-sm">
    <h3>Zweitens</h3>
    <p>
        Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv
        wie Bayern. Letzte Spiel hatten wir in Platz drei Spitzen: Elber, Jancka
        und dann Zickler. Wir müssen nicht vergessen Zickler. Zickler ist eine
        Spitzen mehr, Mehmet eh mehr Basler.
    </p>
</div>

